import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';

const db=new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema public,auth to anon,authenticated,service_role;
grant execute on function auth.uid() to authenticated;
`);
const schema=(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8')).replace('alter publication supabase_realtime add table public.player_progress;','');
await db.exec(schema);

const players=Array.from({length:9},()=>randomUUID());
for(const id of players) await db.query('insert into auth.users(id) values($1)',[id]);
const today=(await db.query("select (now() at time zone 'America/Argentina/Buenos_Aires')::date::text as day")).rows[0].day;
await db.query("insert into nexo_private.days(day,secret) values($1,'CAMINO')",[today]);
await db.exec('set role service_role');
async function call(player,action='state',data={}) {
  return (await db.query('select public.nexo_api($1,$2,$3) as result',[player,action,{requestId:randomUUID(),...data}])).rows[0].result;
}
const a=players[0],b=players[1],c=players[2];
let state=await call(a);
assert.equal(state.progress.prefix,'C');assert.equal(state.secret,null);assert.equal(state.progress.credits,1);
assert(!JSON.stringify(state).includes('CAMINO'));

assert.equal((await call(a)).progress.credits,1);
await assert.rejects(()=>call(a,'create',{word:'PERRO',clue:'Animal domestico que ladra.'}),/prefijo/);
const requestId=randomUUID();
const first=await call(a,'create',{word:'CARACOL',clue:'Molusco con una concha en espiral.',requestId});
const replay=await call(a,'create',{word:'CARACOL',clue:'Molusco con una concha en espiral.',requestId});
assert.deepEqual(replay,first);assert.equal(first.progress.credits,0);assert.equal(first.ownContacts.length,1);
const id=first.ownContacts[0].id;
assert.equal(first.pool.length,0);
await assert.rejects(()=>call(a,'answer',{contactId:id,version:1,guess:'CARACOL'}),/propia/);
const bstate=await call(b);
assert.equal(bstate.pool[0].id,id);
assert(!JSON.stringify(bstate).includes('CARACOL'));
assert(!('word' in bstate.pool[0]));
await call(b,'answer',{contactId:id,version:1,guess:'CARACOL'});
assert.equal((await call(a)).progress.prefix,'C');
await assert.rejects(()=>call(b,'answer',{contactId:id,version:1,guess:'CARACOL'}),/Ya respondiste/);
assert.equal((await call(b)).progress.credits,2);
await assert.rejects(()=>call(a,'rate',{contactId:id,version:1,score:5}),/propia/);
await assert.rejects(()=>call(c,'rate',{contactId:id,version:1,score:5}),/antes/);
await assert.rejects(()=>call(b,'rate',{contactId:id,version:1,score:0}),/1 a 5/);
assert.equal((await call(b)).ratingQueue[0].id,id);
assert(!('word' in (await call(b)).ratingQueue[0]));
const voteId=randomUUID();
const rated=await call(b,'rate',{contactId:id,version:1,score:4,requestId:voteId});
assert.equal(rated.progress.credits,2);assert.equal(rated.ratingQueue.length,0);
assert.deepEqual(await call(b,'rate',{contactId:id,version:1,score:4,requestId:voteId}),rated);
await assert.rejects(()=>call(b,'rate',{contactId:id,version:1,score:5}),/Ya valoraste/);
await call(c,'answer',{contactId:id,version:1,guess:'CARACOL'});
await call(c,'rate',{contactId:id,version:1,score:2});
assert.equal((await call(a)).ownContacts[0].ratingAverage,3);
assert.equal((await call(a)).ownContacts[0].ratingCount,2);
state=await call(a);assert.equal(state.progress.prefix,'CA');assert.equal(state.progress.contacts,1);
assert.equal(state.ownContacts[0].status,'CONFIRMED');
await call(players[3],'answer',{contactId:id,version:1,guess:'CABALLO'});
assert.equal((await call(a)).progress.contacts,1);
await assert.rejects(()=>call(a,'create',{word:'CIELO',clue:'Lo ves cuando miras hacia arriba.'}),/prefijo/);
await db.exec('reset role');
await db.query('update public.player_progress set credits=5 where player_id=$1',[a]);
await db.exec('set role service_role');
state=await call(a,'create',{word:'CADENA',clue:'Eslabones unidos entre si.'});
const editable=state.ownContacts.find(x=>x.word==='CADENA').id;
await call(b,'answer',{contactId:editable,version:1,guess:'CADENA'});
state=await call(a,'edit',{contactId:editable,clue:'Una sucesion de eslabones metalicos unidos.'});
assert.equal(state.ownContacts.find(x=>x.id===editable).matches,0);
await assert.rejects(()=>call(c,'answer',{contactId:editable,version:1,guess:'CADENA'}),/cambió/);
await assert.rejects(()=>call(b,'rate',{contactId:editable,version:1,score:5}),/cambió/);
assert(!(await call(b)).ratingQueue.some(x=>x.id===editable));
assert.equal((await call(a)).ownContacts.find(x=>x.id===editable).ratingCount,0);
await call(c,'answer',{contactId:editable,version:2,guess:'CADENA'});
await call(players[3],'answer',{contactId:editable,version:2,guess:'CADENA'});
assert.equal((await call(a)).progress.prefix,'CAM');
state=await call(a,'create',{word:'CAMELLO',clue:'Animal del desierto con dos jorobas.'});
const reported=state.ownContacts.find(x=>x.word==='CAMELLO').id;
for(const player of players.slice(4,7)) await call(player,'report',{contactId:reported,reason:'other'});
assert.equal((await call(a)).ownContacts.find(x=>x.id===reported).status,'SUSPENDED');
assert(!(await call(players[7])).pool.some(x=>x.id===reported));
await assert.rejects(()=>call(players[7],'answer',{contactId:reported,version:1,guess:'CAMELLO'}),/compatible/);
state=await call(a,'guess',{guess:'CAMISA'});assert.equal(state.progress.status,'PLAYING');assert.equal(state.progress.attempts.length,1);assert.equal(state.secret,null);
state=await call(a,'guess',{guess:'CAMINO'});assert.equal(state.progress.status,'WON');assert.equal(state.secret,'CAMINO');
await assert.rejects(()=>call(a,'guess',{guess:'CAMINO'}),/terminó/);
for(let i=0;i<3;i++) state=await call(players[7],'guess',{guess:'COSA'});
assert.equal(state.progress.status,'LOST');
await call(players[3],'guess',{guess:'CAMINO'});
assert.equal((await call(players[3],'rate',{contactId:id,version:1,score:1})).progress.status,'WON');
assert.equal((await call(a)).ownContacts.find(x=>x.id===id).status,'CONFIRMED');
await assert.rejects(()=>call(players[7],'guess',{guess:'CAMINO'}),/terminó/);
await db.exec('reset role');
await db.exec('set role service_role');
const noOracle=await call(players[8],'create',{word:'CAMINO',clue:'Un trayecto hacia otro sitio.'});
assert.equal(noOracle.secret,null);assert.equal(noOracle.progress.prefix,'C');assert.equal(noOracle.progress.attempts.length,0);
for(let i=0;i<5;i++)assert.equal((await db.query('select public.nexo_allow_request($1,$2) as allowed',[b,'register'])).rows[0].allowed,true);
assert.equal((await db.query('select public.nexo_allow_request($1,$2) as allowed',[b,'register'])).rows[0].allowed,false);
assert.equal((await db.query('select public.nexo_allow_request($1,$2) as allowed',[c,'register'])).rows[0].allowed,true);
await db.exec('reset role');
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);
await db.exec('set role authenticated');
await assert.rejects(()=>db.query('select public.nexo_allow_request($1,$2)',[b,'state']),/permission denied/);
const visible=await db.query('select * from public.player_progress');
assert.equal(visible.rows.length,1);assert.equal(visible.rows[0].player_id,b);
await assert.rejects(()=>db.query('select * from nexo_private.days'),/permission denied/);
await assert.rejects(()=>db.query('select * from nexo_private.ratings'),/permission denied/);
await assert.rejects(()=>db.query('select public.nexo_api($1,$2,$3)',[a,'state',{}]),/permission denied/);
await assert.rejects(()=>db.query('update public.player_progress set credits=100'),/permission denied/);
await db.exec('reset role; set role anon');
await assert.rejects(()=>db.query('select * from public.player_progress'),/permission denied/);
await db.close();
console.log('PASS: daily secret, prefix, private answers, credits, idempotency, independent confirmations, edits, reports, attempts and RLS.');
