import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
let handler,allowed=true,verified=true,captchaSecret='',captchaSiteKey='',captchaReply={success:true,hostname:'contacto.sytes.net',action:'register'},captchaNetworkFailure=false,updates=0;
const consumed=new Set();
const calls=[];
const admin={auth:{getUser:async()=>({data:{user:verified?{id:'verified-user',is_anonymous:true}:null},error:null}),admin:{updateUserById:async()=>{updates++;return {data:{user:{is_anonymous:false}},error:null};}}},rpc:async(name,args)=>{calls.push({name,args});return {data:name==='nexo_allow_request'?allowed:{ok:true},error:null};}};
const source=(await readFile(new URL('../supabase/functions/nexo/index.ts',import.meta.url),'utf8')).replace(/^import .*\n/,'');
runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{exports:{},require:()=>({createClient:()=>admin}),createClient:()=>admin,Deno:{env:{get:key=>key==='TURNSTILE_SECRET_KEY'?captchaSecret:key==='TURNSTILE_SITE_KEY'?captchaSiteKey:''},serve:fn=>{handler=fn;}},Request,Response,TextDecoder,Uint8Array,Set,JSON,URL,AbortSignal,fetch:async(url,options)=>{assert.equal(url,'https://challenges.cloudflare.com/turnstile/v0/siteverify');if(captchaNetworkFailure)throw new Error('offline');const token=JSON.parse(options.body).response;if(consumed.has(token))return Response.json({success:false});if(captchaReply.success)consumed.add(token);return Response.json(captchaReply);}});
const request=(body,headers={})=>new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer valid',...headers},body:JSON.stringify(body)});
assert.equal((await handler(new Request('https://example.test',{method:'POST'}))).status,401);
assert.equal((await handler(request({action:'state'},{origin:'https://evil.test'}))).status,403);
verified=false;assert.equal((await handler(request({action:'state'}))).status,401);verified=true;
assert.equal((await handler(request({action:'state',data:[]}))).status,400);
assert.equal((await handler(request({action:'state',data:{padding:'ñ'.repeat(3000)}}))).status,413);
assert.equal((await handler(request({action:'state',data:{player:'forged-user'}}))).status,200);
assert.equal(calls.at(-1).args.p_player,'verified-user');
allowed=false;const blocked=await handler(request({action:'guess',data:{guess:'TEST'}}));assert.equal(blocked.status,429);assert.equal(calls.at(-1).name,'nexo_allow_request');
console.log('PASS: Edge rejects missing/invalid identity, untrusted origins, malformed and oversized bodies; uses verified UUID and enforces rate limits before game operations.');

allowed=true;
assert.equal((await handler(request({action:'answer',data:{}}))).status,200);
assert.equal(calls.at(-2).args.p_scope,'answer');
assert.equal((await handler(request({action:'report',data:{}}))).status,200);
assert.equal(calls.at(-2).args.p_scope,'report');
assert.deepEqual(await (await handler(request({action:'registration-config'}))).json(),{required:false,siteKey:''});
captchaSecret='test-secret';
assert.equal((await handler(request({action:'registration-config'}))).status,503,'Partial configuration must fail closed.');
captchaSiteKey='test-site-key';
assert.deepEqual(await (await handler(request({action:'registration-config'}))).json(),{required:true,siteKey:'test-site-key'});
const registration=token=>request({action:'register',data:{username:'captchatest',password:'safe-test-password',captchaToken:token}});
assert.equal((await handler(registration(''))).status,400);
assert.equal((await handler(registration('x'.repeat(2049)))).status,400);
captchaReply={success:false};assert.equal((await handler(registration('invalid'))).status,400);
captchaReply={success:true,hostname:'evil.test',action:'register'};assert.equal((await handler(registration('badhost'))).status,400);
captchaReply={success:true,hostname:'contacto.sytes.net',action:'other'};assert.equal((await handler(registration('badaction'))).status,400);
captchaNetworkFailure=true;assert.equal((await handler(registration('offline'))).status,503);captchaNetworkFailure=false;
assert.equal(updates,0,'A rejected CAPTCHA must never create an account.');
captchaReply={success:true,hostname:'contacto.sytes.net',action:'register'};
assert.equal((await handler(registration('valid-once'))).status,200);assert.equal(updates,1);
assert.equal((await handler(registration('valid-once'))).status,400);assert.equal(updates,1);
assert.equal((await handler(request({action:'state'}))).status,200,'Guest play does not require a CAPTCHA.');
console.log('PASS: CAPTCHA is verified server-side, checks hostname/action, rejects replay and provider failure; guests remain playable and action limits are separate.');
