import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
let handler,allowed=true,verified=true;
const calls=[];
const admin={auth:{getUser:async()=>({data:{user:verified?{id:'verified-user',is_anonymous:true}:null},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {data:name==='nexo_allow_request'?allowed:{ok:true},error:null};}};
const source=(await readFile(new URL('../supabase/functions/nexo/index.ts',import.meta.url),'utf8')).replace(/^import .*\n/,'');
runInNewContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,{exports:{},require:()=>({createClient:()=>admin}),createClient:()=>admin,Deno:{env:{get:()=>''},serve:fn=>{handler=fn;}},Request,Response,TextDecoder,Uint8Array,Set,JSON});
const request=(body,headers={})=>new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer valid',...headers},body:JSON.stringify(body)});
assert.equal((await handler(new Request('https://example.test',{method:'POST'}))).status,401);
assert.equal((await handler(request({action:'state'},{origin:'https://evil.test'}))).status,403);
verified=false;assert.equal((await handler(request({action:'state'}))).status,401);verified=true;
assert.equal((await handler(request({action:'state',data:[]}))).status,400);
assert.equal((await handler(request({action:'state',data:{padding:'ñ'.repeat(3000)}}))).status,413);
assert.equal((await handler(request({action:'state',data:{player:'forged-user'}}))).status,200);
assert.equal(calls.at(-1).args.p_player,'verified-user');
allowed=false;const blocked=await handler(request({action:'guess',data:{guess:'TEST'}}));assert.equal(blocked.status,429);assert.equal(calls.at(-1).name,'nexo_allow_request');
console.log('PASS: Edge rejects missing/invalid identity, untrusted origins, malformed and oversized bodies; uses verified UUID and enforces rate limits before game operations.');
